### PR TITLE
SDT-115: Added approval for application gateway module to civil-sdt-gateway

### PR DESCRIPTION
**Pull request by paulridout**
Added approval for application gateway module to civil-sdt-gateway

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
@TomKimber is this right shouldn't they be using a central one?

**Comment by paulridout** [comment]
As a bit of background, terraform-module-apim-application-gateway was changed to support mTLS termination under https://tools.hmcts.net/jira/browse/DTSPO-13622.  This change was required for the SDT replacement project.

**Comment by timja** [comment]
cc @cpareek is the intention that these guys deploy their own app gateway instead of using a central one?

**Comment by timja** [comment]
also @thomast1906

**Comment by paulridout** [comment]
There's some further background on https://tools.hmcts.net/jira/browse/DTSPO-5696 around the reasons for setting this up.  @richardrothery and @thomast1906 were involved in the discussions around it.

**Comment by timja** [comment]
I understand the reasons for it but not why you are deploying your own gateway rather than using a central one

**Comment by timja** [comment]
I pinged Richard on Slack and he understands the same as me:

> Richard Rothery
:spiral_calendar_pad:  [2:27 PM](https://hmcts-reform.slack.com/archives/C029G7FBHB6/p1691414873590839)
yup afaik we should be using the central ones Thomas already built and just adding new URLs / routing rules to them…

**Comment by paulridout** [comment]
My fault - I misunderstood how terraform-module-apim-application-gateway was going to be used.  Closing this pull request.

**Pull request closed without merging**
