### PR TITLE
DTSRD-1205

### PR DESCRIPTION
**Pull request by andy-m-b**
- Adding azurerm_role_assignment due to failing Jenkins build for rd-shared-infrastructure PR.

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

Notes:
* There is a failing build for a PR on rd-shared-infrastructure - https://build.hmcts.net/blue/organizations/jenkins/HMCTS_j_to_z%2Frd-shared-infrastructure/detail/PR-212/1/pipeline/
* This repo is using a terraform resource that is not allowed,
whitelists are stored in https://github.com/hmcts/cnp-jenkins-config/tree/master/terraform-infra-approvals
send a pull request if you think this is in error.
non whitelisted resources:
```
[{managed azurerm_pim_eligible_role_assignment this {azurerm } {storage-account-rd-data-extracts.tf 79}}]

### CODE REVIEW

**Review by timja — COMMENTED** [review]
It would be better if support for this could be added to cnp-module-storage-account instead?
https://github.com/hmcts/cnp-module-storage-account?tab=readme-ov-file#how-to-use-this-module

Do you think you would be able to do that?

**Comment by andy-m-b** [comment]
Hi @timja yes I am happy to look at whatever way is preferable - apologies I am confused about what you mean by adding support however - from what I can see the role assignment is included in cnp-module-storage-account https://github.com/hmcts/cnp-module-storage-account/blob/master/main.tf#L109, and this is what I am trying to implement in our PR that uses this module as its basis - https://github.com/hmcts/rd-shared-infrastructure/pull/204/files

**Comment by timja** [comment]
> Hi @timja yes I am happy to look at whatever way is preferable - apologies I am confused about what you mean by adding support however - from what I can see the role assignment is included in cnp-module-storage-account [hmcts/cnp-module-storage-account@`master`/main.tf#L109](https://github.com/hmcts/cnp-module-storage-account/blob/master/main.tf?rgh-link-date=2023-11-13T15%3A02%3A28Z#L109), and this is what I am trying to implement in our PR that uses this module as its basis - [hmcts/rd-shared-infrastructure#204 (files)](https://github.com/hmcts/rd-shared-infrastructure/pull/204/files)

That one only supports granting the application's identity here.
I assume you're trying to give people access?

In that case you'll need a separate use of the resource probably with a list of objects, maybe something like:

```terraform
additional_role_assignments = [
 {
   role_name   = "Storage Blob Delegator"
   principal_id = "..."
 }
]
```

**Comment by andy-m-b** [comment]
Ok thank you I will take a look.

I am trying to do this which you recommended in a previous ticket, I think to allow plat ops to create user delegation SAS tokens https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1698831654531359?thread_ts=1697701798.065369&cid=C8SR5CAMU

> > Hi @timja yes I am happy to look at whatever way is preferable - apologies I am confused about what you mean by adding support however - from what I can see the role assignment is included in cnp-module-storage-account [hmcts/cnp-module-storage-account@`master`/main.tf#L109](https://github.com/hmcts/cnp-module-storage-account/blob/master/main.tf?rgh-link-date=2023-11-13T15%3A02%3A28Z#L109), and this is what I am trying to implement in our PR that uses this module as its basis - [hmcts/rd-shared-infrastructure#204 (files)](https://github.com/hmcts/rd-shared-infrastructure/pull/204/files)
> 
> That one only supports granting the application's identity here. I assume you're trying to give people access?
> 
> In that case you'll need a separate use of the resource probably with a list of objects, maybe something like:
> 
> ```terraform
> additional_role_assignments = [
>  {
>    role_name   = "Storage Blob Delegator"
>    principal_id = "..."
>  }
> ]
> ```

Ok thank you I will take a look.

I am trying to do this which you recommended in a previous ticket, I think to allow plat ops to create user delegation SAS tokens https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1698831654531359?thread_ts=1697701798.065369&cid=C8SR5CAMU

**Comment by andy-m-b** [comment]
Ok thank you @timja I will take a look.

I am trying to do this which you recommended in a previous ticket, I think to allow plat ops to create user delegation SAS tokens https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1698831654531359?thread_ts=1697701798.065369&cid=C8SR5CAMU

**Comment by andy-m-b** [comment]
Currently Ieuan who is only able to generate an Account Key SAS token, not the user delegation so I believe this is the last change I need to make to set up as desired.

**Comment by andy-m-b** [comment]
https://github.com/hmcts/rd-shared-infrastructure/pull/204/files#diff-a0b49b65afa0ddafa8a6d14b1bf336fe43d7a770bf33194348db0c5d9ad45660R11

@timja I have referred to the _role_assignments_ list inside the the _azurerm_role_assignment_ resource in our PR - does this achieve the same as the _additional_role_assignments_ list you have suggested? I am just trying to understand why an additional list is needed and how it differs from the existing role_assignments list in  cnp-module-storage-account.

**Comment by timja** [comment]
> [hmcts/rd-shared-infrastructure#204 (files)](https://github.com/hmcts/rd-shared-infrastructure/pull/204/files#diff-a0b49b65afa0ddafa8a6d14b1bf336fe43d7a770bf33194348db0c5d9ad45660R11)
> 
> @timja I have referred to the _role_assignments_ list inside the the _azurerm_role_assignment_ resource in our PR - does this achieve the same as the _additional_role_assignments_ list you have suggested? I am just trying to understand why an additional list is needed and how it differs from the existing _role_assignments_ list in cnp-module-storage-account.

Your code would end up granting these roles:

-    Storage Account Delegator
-    Storage Blob Delegator

To `rd_product_group_object_id` 

I'm not sure why you defined a longer list and then filtered it down to just those 2 groups.

----

I would still prefer if this was in the module itself but I guess this might be a bit safer as it restricts it to just your team

**Comment by timja** [comment]
> Sorry but I am still a bit lost as to what change you would like me to make - do you want me to add 'Storage Account Delegator' to the allowed_roles in the cnp-module-storage-account and add the list to the variables file as defaults, instead of doing this in rd-shared-infrastructure?

I'll make a change to the module with something that I think should work for you.

ETA today, is that okay?

**Pull request closed without merging**
